FROM golang:1.24.5-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git ca-certificates
COPY . .
ENV GOPROXY=https://proxy.golang.org,direct

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server .

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app

COPY --from=builder /app/server ./server

COPY --from=builder /app/templates ./templates
COPY --from=builder /app/static ./static

EXPOSE 8080
CMD ["./server"]

